package com.example.ui

object Localization {

    private val ar = mapOf(
        "app_title" to "المسلم الشامل",
        "home" to "الرئيسية",
        "prayers" to "مواقيت الصلاة",
        "quran" to "القرآن الكريم",
        "azkar" to "الأذكار",
        "tasbih" to "السبحة",
        "qibla" to "القبلة",
        "sync" to "المزامنة",
        "settings" to "الإعدادات",
        "fajr" to "الفجر",
        "sunrise" to "الشروق",
        "dhuhr" to "الظهر",
        "asr" to "العصر",
        "maghrib" to "المغرب",
        "isha" to "العشاء",
        "azan_alert" to "تنبيه الأذان",
        "voice" to "أصوات المؤذنين",
        "selected_city" to "المدينة الحالية",
        "custom_coordinate" to "تخصيص الإحداثيات",
        "lat" to "خط العرض",
        "lng" to "خط الطول",
        "save" to "حفظ",
        "quran_search" to "البحث المتقدم في القرآن",
        "search_hint" to "اكتب كلمة للبحث (مثال: أحد، الصمد، العصر)",
        "no_results" to "لا توجد نتائج مطابقة",
        "verse" to "آية",
        "notes" to "الملاحظات والتفاسير",
        "add_note" to "إضافة ملاحظة للآية",
        "note_hint" to "اكتب تفسيراً أو خاطرة شخصية هنا...",
        "view_tafsir" to "تفسير الآية",
        "bookmarks" to "العلامات المرجعية",
        "khatm_scheduler" to "جدول الختمة اليومية",
        "active_goal" to "هدفك الحالي",
        "pages_left" to "صفحة متبقية للختم",
        "pages_done" to "تمت قراءتها",
        "days_left" to "أيام متبقية",
        "khatm_hint" to "حدد مدة الختمة بالأيام لتخصيص جدولك اليومي:",
        "start_khatm" to "ابدأ ختمة جديدة",
        "days" to "يوم",
        "daily_target" to "الهدف اليومي",
        "history_log" to "سجل القراءة الشخصي",
        "log_pages" to "تسجيل قراءة صفحات",
        "log_pages_button" to "سجل قراءة",
        "performance_report" to "تقارير إنجاز الختم",
        "tasbih_electronic" to "السبحة الإلكترونية",
        "total_tasbih" to "إجمالي التسبيحات",
        "target" to "الهدف",
        "reset" to "إعادة ضبط",
        "new_tasbih" to "إضافة تسبيحة مخصصة",
        "phrase_hint" to "اكتب الذكر (مثال: أستغفر الله العظيم)",
        "add_phrase" to "إضافة",
        "compass_qibla" to "بوصلة تحديد القبلة بدقة",
        "calibrate" to "معايرة البوصلة",
        "mecca_dist" to "المسافة الكروية التقريبية لمكة",
        "sync_cloud" to "النسخ الاحتياطي السحابي المتعدد والمزامنة",
        "sync_desc" to "قم بنسخ وحفظ سجلاتك وملاحظاتك الشخصية لمزامنتها آلياً عبر أجهزتك المختلفة بدون اتصال دائم.",
        "backup_now" to "نسخ احتياطي فوري لشحنة البيانات",
        "restore_now" to "استعادة البيانات من شحنة سابقة",
        "paste_json" to "ألصق شفرة البيانات المسترجعة هنا لنسخها واسترجاعها:",
        "backup_code" to "شفرة النسخ الاحتياطي الخاصة بك",
        "copy_code" to "نسخ الشفرة",
        "devices_sync" to "الموجات النشطة للمزامنة المتعددة للشبكة اللامركزية",
        "sync_active" to "المزامنة نشطة الآن",
        "azan_notif_played" to "تم تشغيل محاكاة صوت الأذان بصوت المؤذن: ",
        "tafsir_title" to "التفسير الميسر",
        "surah_details" to "تفاصيل السورة",
        "juristic" to "المذهب الفقهي (العصر)",
        "calc_auth" to "طريقة الحساب الفلكي",
        "dark_mode" to "الوضع المظلم لراحة العين",
        "lang_switch" to "لغة التطبيق"
    )

    private val en = mapOf(
        "app_title" to "Al-Muslim Al-Shamel",
        "home" to "Home",
        "prayers" to "Prayer Times",
        "quran" to "Holy Quran",
        "azkar" to "Azkar",
        "tasbih" to "Tasbih",
        "qibla" to "Qibla Direction",
        "sync" to "Sync & Backup",
        "settings" to "Settings",
        "fajr" to "Fajr",
        "sunrise" to "Sunrise",
        "dhuhr" to "Dhuhr",
        "asr" to "Asr",
        "maghrib" to "Maghrib",
        "isha" to "Isha",
        "azan_alert" to "Azan Notification",
        "voice" to "Muezzin Voices",
        "selected_city" to "Selected City",
        "custom_coordinate" to "Custom Coordinate",
        "lat" to "Latitude",
        "lng" to "Longitude",
        "save" to "Save",
        "quran_search" to "Advanced Quran Search",
        "search_hint" to "Type a keyword (e.g. One, Samad, Asr)",
        "no_results" to "No matching results",
        "verse" to "Verse",
        "notes" to "Notes & Interpretations",
        "add_note" to "Add Verse Note",
        "note_hint" to "Type a personal reflection or notes...",
        "view_tafsir" to "Verse Tafsir",
        "bookmarks" to "Bookmarks",
        "khatm_scheduler" to "Daily Khatm Scheduler",
        "active_goal" to "Active Khatm Goal",
        "pages_left" to "pages left to finish",
        "pages_done" to "pages read",
        "days_left" to "days remaining",
        "khatm_hint" to "Specify Khatm duration in days to customize goals:",
        "start_khatm" to "Start New Khatm",
        "days" to "Days",
        "daily_target" to "Daily Target",
        "history_log" to "Personal Reading History",
        "log_pages" to "Log Read Pages",
        "log_pages_button" to "Log Reading",
        "performance_report" to "Periodic Progress Report",
        "tasbih_electronic" to "Electronic Tasbih Rosary",
        "total_tasbih" to "Total Counts",
        "target" to "Target",
        "reset" to "Reset",
        "new_tasbih" to "Add Custom Tasbih",
        "phrase_hint" to "Type phrase (e.g. Subhan Allah)",
        "add_phrase" to "Add",
        "compass_qibla" to "High-Precision Qibla Compass",
        "calibrate" to "Calibrate Sensor Compass",
        "mecca_dist" to "Approx Spherical Distance to Mecca",
        "sync_cloud" to "Multi-Device Cloud Backup & Sync",
        "sync_desc" to "Safely backup and restore your personal goals, history, and notes to synchronize them across devices without perpetual internet.",
        "backup_now" to "Generate Backup Ship",
        "restore_now" to "Restore Data Ship",
        "paste_json" to "Paste previous backup data string here to restore:",
        "backup_code" to "Your Backup Data String",
        "copy_code" to "Copy Code",
        "devices_sync" to "Decentralized Peer Network Active Wave",
        "sync_active" to "Sync is fully active",
        "azan_notif_played" to "Azan notification simulated successfully with voice: ",
        "tafsir_title" to "Clear Verse Tafsir",
        "surah_details" to "Surah Details",
        "juristic" to "Juristic Method (Asr)",
        "calc_auth" to "Astronomy Calc Method",
        "dark_mode" to "Dark Mode for Eye Strain",
        "lang_switch" to "Application Language"
    )

    private val tr = mapOf(
        "app_title" to "Müslüman Azığı",
        "home" to "Ana Sayfa",
        "prayers" to "Namaz Vakitleri",
        "quran" to "Kur\\'an-ı Kerim",
        "azkar" to "Dualar",
        "tasbih" to "Zikirmatik",
        "qibla" to "Kıble Yönü",
        "sync" to "Yedekle & Eşitle",
        "settings" to "Ayarlar",
        "fajr" to "İmsak",
        "sunrise" to "Güneş",
        "dhuhr" to "Öğle",
        "asr" to "İkindi",
        "maghrib" to "Akşam",
        "isha" to "Yatsı",
        "azan_alert" to "Ezan Bildirimi",
        "voice" to "Müezzin Sesi",
        "selected_city" to "Seçilen Şehir",
        "custom_coordinate" to "Koordinat Belirle",
        "lat" to "Enlem",
        "lng" to "Boylam",
        "save" to "Kaydet",
        "quran_search" to "Gelişmiş Kur\\'an Arama",
        "search_hint" to "Arama yapmak için kelime yazın",
        "no_results" to "Sonuç bulunamadı",
        "verse" to "Ayet",
        "notes" to "Kişisel Ayet Notları",
        "add_note" to "Ayete Not Ekle",
        "note_hint" to "Kişisel düşüncenizi veya tefsiri yazın...",
        "view_tafsir" to "Ayet Tefsiri",
        "bookmarks" to "Yer İmleri",
        "khatm_scheduler" to "Günlük Hatim Çizelgesi",
        "active_goal" to "Güncel Hatim Hedefiniz",
        "pages_left" to "sayfa kaldı",
        "pages_done" to "okunan sayfa",
        "days_left" to "gün kaldı",
        "khatm_hint" to "Hatim süresini gün cinsinden belirleyin:",
        "start_khatm" to "Hatim Başlat",
        "days" to "Gün",
        "daily_target" to "Günlük Hedef",
        "history_log" to "Okuma Günlüğü",
        "log_pages" to "Okunan Sayfaları Gir",
        "log_pages_button" to "Kaydet",
        "performance_report" to "Hatim İlerleme Raporu",
        "tasbih_electronic" to "Zikirmatik Tesbih",
        "total_tasbih" to "Toplam Zikir",
        "target" to "Hedef",
        "reset" to "Sıfırla",
        "new_tasbih" to "Yeni Zikir Ekle",
        "phrase_hint" to "Zikir yazın (örneğin: Elhamdülillah)",
        "add_phrase" to "Ekle",
        "compass_qibla" to "Hassas Kıble Pusulası",
        "calibrate" to "Pusulayı Kalibre Et",
        "mecca_dist" to "Mekke\\'ye Küresel Uzaklık",
        "sync_cloud" to "Cihazlar Arası Bulut Yedekleme",
        "sync_desc" to "Okuma kayıtlarınızı, notlarınızı ve hedeflerinizi internet olmadan cihazlar arasında senkronize edin.",
        "backup_now" to "Yedek Kodu Üret",
        "restore_now" to "Yedeği Geri Yükle",
        "paste_json" to "Yedek kodunu buraya yapıştırın:",
        "backup_code" to "Yedek Veri Kodu",
        "copy_code" to "Kodu Kopyala",
        "devices_sync" to "Aktif Ağ Senkronizasyonu",
        "sync_active" to "Senkronizasyon aktif",
        "azan_notif_played" to "Ezan sesi canlandırıldı: ",
        "tafsir_title" to "Ayet Tefsiri",
        "surah_details" to "Sure Detayları",
        "juristic" to "Fıkıh Mezhebi",
        "calc_auth" to "Astronomi Hesaplama",
        "dark_mode" to "Göz Sağlığı için Koyu Mod",
        "lang_switch" to "Uygulama Dili"
    )

    private val ur = mapOf(
        "app_title" to "المسلم الشامل",
        "home" to "ہوم",
        "prayers" to "اوقات نماز",
        "quran" to "قرآن کریم",
        "azkar" to "اذکار",
        "tasbih" to "تسبیح",
        "qibla" to "قبلہ رخ",
        "sync" to "بیک اپ اور مطابقت",
        "settings" to "ترتیبات",
        "fajr" to "فجر",
        "sunrise" to "طلوعِ آفتاب",
        "dhuhr" to "ظہر",
        "asr" to "عصر",
        "maghrib" to "مغرب",
        "isha" to "عشاء",
        "azan_alert" to "اذان الرٹ",
        "voice" to "مؤذن کی آوازیں",
        "selected_city" to "منتخب شہر",
        "custom_coordinate" to "درست لوکیشن بنائیں",
        "lat" to "عرض بلد",
        "lng" to "طول بلد",
        "save" to "محفوظ کریں",
        "quran_search" to "قرآن میں جدید ترین تلاش",
        "search_hint" to "تلاش کے لیے لفظ لکھیں (مثال: احد)",
        "no_results" to "کوئی نتیجہ نہیں ملا",
        "verse" to "آیت",
        "notes" to "کمنٹس اور تفاسیر",
        "add_note" to "آیت پر نوٹ تحریر کریں",
        "note_hint" to "اپنے خیالات یا ذاتی غور و فکر لکھیں...",
        "view_tafsir" to "آیت کی تفسیر",
        "bookmarks" to "بک مارکس",
        "khatm_scheduler" to "روزانہ تلاوتِ قرآن کا شیڈول",
        "active_goal" to "آپ کا موجودہ ہدف",
        "pages_left" to "صفحات باقی ہیں",
        "pages_done" to "مکمل صفحات",
        "days_left" to "باقی دن",
        "khatm_hint" to "قرآن ختم کرنے کی مدت دنوں میں مقرر کریں:",
        "start_khatm" to "نیا دورِ تلاوت شروع کریں",
        "days" to "دن",
        "daily_target" to "روزانہ کا ہدف",
        "history_log" to "تلاوت کا ذاتی ریکارڈ",
        "log_pages" to "پڑھے گئے صفحات درج کریں",
        "log_pages_button" to "محفوظ کریں",
        "performance_report" to "تلاوت کی تفصیلی رپورٹ",
        "tasbih_electronic" to "الیکٹرانک ڈیجیٹل تسبیح",
        "total_tasbih" to "کل تعداد",
        "target" to "ہدف",
        "reset" to "دوبارہ شروع",
        "new_tasbih" to "اپنی پسند کا ذکر شامل کریں",
        "phrase_hint" to "ذکر لکھیں (مثال: سبحان اللہ)",
        "add_phrase" to "شامل کریں",
        "compass_qibla" to "قبلہ رخ معلوم کرنے کا درست کمپاس",
        "calibrate" to "کمپاس کی درستگی",
        "mecca_dist" to "مکہ مکرمہ سے فضائی فاصلہ",
        "sync_cloud" to "ملٹی ڈیوائس کلاؤڈ بیک اپ",
        "sync_desc" to "اپنا ریکارڈ، تاریخ اور نوٹس مختلف آلات پر بیک اپ کے ذریعے بغیر مستقل انٹرنیٹ کے منتقل کریں۔",
        "backup_now" to "بیک اپ کوڈ بنائیں",
        "restore_now" to "ڈیٹا ری سٹور کریں",
        "paste_json" to "بیک اپ کوڈ یہاں چسپاں کریں:",
        "backup_code" to "آپ کا بیک اپ کوڈ",
        "copy_code" to "کوڈ کاپی کریں",
        "devices_sync" to "لوکل نیٹ ورک سنکرونائزیشن چالو ہے",
        "sync_active" to "سنکرونائزیشن ایکٹو ہے",
        "azan_notif_played" to "اذان کی آواز چلائی گئی: ",
        "tafsir_title" to "آیت کی آسان تفسیر",
        "surah_details" to "سورت کی تفصیلات",
        "juristic" to "فقہی مسلک",
        "calc_auth" to "فلکیاتی حساب کا طریقہ",
        "dark_mode" to "آنکھوں کے سکون کے لیے ڈارک موڈ",
        "lang_switch" to "درخواست کی زبان"
    )

    private val fr = mapOf(
        "app_title" to "Moisson du Musulman",
        "home" to "Accueil",
        "prayers" to "Horaires Prière",
        "quran" to "Saint Coran",
        "azkar" to "Azkar invocations",
        "tasbih" to "Chapelet digital",
        "qibla" to "Direction Qibla",
        "sync" to "Sauvegarde & Sync",
        "settings" to "Paramètres",
        "fajr" to "Fajr",
        "sunrise" to "Lever du soleil",
        "dhuhr" to "Dhuhr",
        "asr" to "Asr",
        "maghrib" to "Maghrib",
        "isha" to "Isha",
        "azan_alert" to "Notification Adhan",
        "voice" to "Voix Muezzin",
        "selected_city" to "Ville sélectionnée",
        "custom_coordinate" to "Personnaliser coord.",
        "lat" to "Latitude",
        "lng" to "Longitude",
        "save" to "Enregistrer",
        "quran_search" to "Recherche Avancée Coran",
        "search_hint" to "Tapez un mot à chercher (ex: Un, Samad, Asr)",
        "no_results" to "Aucun résultat trouvé",
        "verse" to "Verset",
        "notes" to "Notes & Commentaires",
        "add_note" to "Ajouter Note au Verset",
        "note_hint" to "Écrivez une réflexion personnelle ou commentaire...",
        "view_tafsir" to "Tafsir du Verset",
        "bookmarks" to "Signets",
        "khatm_scheduler" to "Planificateur de Khatm",
        "active_goal" to "Objectif actif de Khatm",
        "pages_left" to "pages de lecture restantes",
        "pages_done" to "pages lues",
        "days_left" to "jours restants",
        "khatm_hint" to "Durée du Khatm en jours pour planifier :",
        "start_khatm" to "Lancer un nouveau Khatm",
        "days" to "Jours",
        "daily_target" to "Objectif quotidien",
        "history_log" to "Historique de Lecture",
        "log_pages" to "Saisir pages lues",
        "log_pages_button" to "Sauvegarder lecture",
        "performance_report" to "Rapport d\\'avancement Coran",
        "tasbih_electronic" to "Chapelet Électronique",
        "total_tasbih" to "Total égrené",
        "target" to "Objectif",
        "reset" to "Réinitialiser",
        "new_tasbih" to "Ajouter un zikr personnalisé",
        "phrase_hint" to "Tapez zikr (ex: Al hamdou lillah)",
        "add_phrase" to "Ajouter",
        "compass_qibla" to "Boussole de Qibla de Précision",
        "calibrate" to "Calibrer Boussole",
        "mecca_dist" to "Distance sphérique à la Mecque",
        "sync_cloud" to "Sauvegarde Cloud Multi-Cibles",
        "sync_desc" to "Sauvegardez vos lectures, historique et notes pour synchroniser plusieurs appareils sans connexion permanente.",
        "backup_now" to "Générer la Sauvegarde",
        "restore_now" to "Restaurer Sauvegarde",
        "paste_json" to "Coller le code JSON précédent ici :",
        "backup_code" to "Votre code de données de sauvegarde",
        "copy_code" to "Copier le code",
        "devices_sync" to "Réseau de Sync active décentralisé",
        "sync_active" to "Mode synchronisation en cours",
        "azan_notif_played" to "L\\'Adhan a été simulé avec succès, récitant : ",
        "tafsir_title" to "Tafsir du Verset",
        "surah_details" to "Détails de la Sourate",
        "juristic" to "Méthode Juridique (Asr)",
        "calc_auth" to "Méthode astronomique",
        "dark_mode" to "Mode Sombre pour la fatigue oculaire",
        "lang_switch" to "Langue de l\\'application"
    )

    fun get(key: String, lang: String): String {
        val dict = when (lang) {
            "en" -> en
            "tr" -> tr
            "ur" -> ur
            "fr" -> fr
            else -> ar
        }
        return dict[key] ?: key
    }
}
